
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        auto_quote_keyword: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    converters:
      preferred-json-mapper: jackson

server:
  port: 8080

key:
  access: ${ACCESS_KEY}
  refresh: ${REFRESH_KEY}

cloud:
  aws:
    s3:
      endpoint: ${SPACES_ENDPOINT}
      bucket: ${SPACES_BUCKET}
      access-key: ${SPACES_ACCESS_KEY}
      secret-key: ${SPACES_SECRET_KEY}

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB

