spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/platform
    username: postgres
    password: qwerty007
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        auto_quote_keyword: true